# Rubocop configuration settings applied to all files in the `diffux` repo.
#
# If you want to override the configuration for a particular directory in the
# repo, add a `.rubocop.yml` file to that directory and make it `inherit_from`
# this file, using a relative path.

# Enable Rails-related checks
AllCops:
  RunRailsCops: true
  Excludes:
    - db/**

MethodLength:
  CountComments: false
  Max: 15

# Prefer curly braces except for %i/%w/%W, since those return arrays.
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# This isn't fully baked yet as it doesn't allow you to disable it for
# multiline argument lists.
TrailingComma:
  Enabled: false
